# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe59b32bd1c6cf8808f20d4fbb87e0a9e24edd31a6913394f1cb1ce4f95ba2d71ab5f68331a89c58f4c0f2ce26afca77db33bf160b3525ef90de4329ecf7ab3d

test:
  secret_key_base: 0713eb622f51ceefdfac18bf007d765607c1f6af64d4bb082df0bffd10825e0f85f5cd15ca6bec7630e1cca0d29d489f2cda3429881c587f49de856348572e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
